### ISSUE TITLE
Unclear how to install

### ISSUE THREAD

**Issue by im-neil** [zzyzzyzzx/Hadar#18]
Installed the plugin manager and it works, but when installing Spellup_Caster, I get the following error:

Run-time error
Plugin: Hadar_Spellup_Caster (called from world: Aardwolf)
Function/Sub: OnPluginInstall called by Plugin Hadar_Spellup_Caster
Reason: Executing plugin Hadar_Spellup_Caster sub OnPluginInstall
[string "Plugin: Hadar_Spellup_Caster"]:229: attempt to index a nil value
stack traceback:
        [string "Plugin: Hadar_Spellup_Caster"]:229: in function 'OnPluginEnable'
        [string "Plugin: Hadar_Spellup_Caster"]:184: in function <[string "Plugin: Hadar_Spellup_Caster"]:175>

What prerequisites are required? For example, do I need to download 'CommonFiles' and put them in a specific place?

**Comment by im-neil** [comment]
Problem resolved by closing mushclient, deleting the plugin state file, and then restarting mushclient.

In my case, the state file was \plugins\state\e0eb198d8d5698e3b2f61483-d2b6d276d6d22cf20d77d46f-state.xml

**Comment by lightsrage** [comment]
I have a question how do blind people use this here plugin manager. I cant seem to be able to activate the buttons in mush from my output window. mind you I am using the vi client. I would love to use the spellup plugin. I looked for the raw button to save the xml file but github was being mean for ahile watch me go back and find it. I saw lots of add coment to line if anyone knows what to do let me know Jenni in game lightsrage#4971 on discord.

**Comment by zzyzzyzzx** [comment]
> 

Yeah my plug-in manager in the current state is not very VI friendly sadly. I am working on V2 of the plug-in manager which will be more friendly. I'll move that to the top of my list

I'm also going to close this topic since it's not related please feel free to open another issue.

Here is a link to the raw to help you
https://raw.githubusercontent.com/zzyzzyzzx/Hadar/master/SpellupRecast/Hadar_Spellups.xml
